package com.limitlesser.bestpractice.model


val MIME_Map = mapOf(
        "jar" to "application/java-archive",
        "doc" to "application/msword",
        "bin" to "application/octet-stream",
        "class" to "application/octet-stream",
        "exe" to "application/octet-stream",
        "pdf" to "application/pdf",
        "rtf" to "application/rtf",
        "apk" to "application/vnd.android.package-archive",
        "mpc" to "application/vnd.mpohun.certificate",
        "msg" to "application/vnd.ms-outlook",
        "pps" to "application/vnd.ms-powerpoint",
        "ppt" to "application/vnd.ms-powerpoint",
        "wps" to "application/vnd.ms-works",
        "z" to "application/x-compress",
        "tgz" to "application/x-compressed",
        "gtar" to "application/x-gtar",
        "gz" to "application/x-gzip",
        "js" to "application/x-javascript",
        "rar" to "application/x-rar-compressed",
        "tar" to "application/x-tar",
        "zip" to "application/zip",

        "amr" to "audio/amr",
        "m4a" to "audio/mp4a-latm",
        "m4b" to "audio/mp4a-latm",
        "m4p" to "audio/mp4a-latm",
        "mpga" to "audio/mpeg",
        "ogg" to "audio/ogg",
        "mp2" to "audio/x-mpeg",
        "mp3" to "audio/x-mpeg",
        "m3u" to "audio/x-mpegurl",
        "wma" to "audio/x-ms-wma",
        "wmv" to "audio/x-ms-wmv",
        "wav" to "audio/x-wav",

        "bmp" to "image/bmp",
        "gif" to "image/gif",
        "jpeg" to "image/jpeg",
        "jpg" to "image/jpeg",
        "png" to "image/png",
        "webp" to "image/webp",

        "htm" to "text/html",
        "html" to "text/html",
        "c" to "text/plain",
        "conf" to "text/plain",
        "cpp" to "text/plain",
        "h" to "text/plain",
        "java" to "text/plain",
        "log" to "text/plain",
        "prop" to "text/plain",
        "rc" to "text/plain",
        "sh" to "text/plain",
        "txt" to "text/plain",
        "xml" to "text/plain",
        "md" to "text/plain",

        "3gp" to "video/3gpp",
        "mp4" to "video/mp4",
        "mpg4" to "video/mp4",
        "mpe" to "video/mpeg",
        "mpeg" to "video/mpeg",
        "mpg" to "video/mpeg",
        "mov" to "video/quicktime",
        "m4u" to "video/vnd.mpegurl",
        "m4v" to "video/x-m4v",
        "asf" to "video/x-ms-asf",
        "avi" to "video/x-msvideo"
)